language: node_js
node_js:
  - stable
before_script: cd services/app
cache: npm
script: make lint
notifications:
  slack:
    secure: vNxHD2FcRQViwBhSWgybq/ZSPy/h8/sFQXKLELhGOwOS15gmERBZslQyFCqJOye6VQCN9e2ANPtT+4c9YN5AbuPdry9a5R0mrKyYmsNwhD2itXfaRkLCMGyJKn8TBfoeHiMXGq/9KVPTAX1gVJ9lFNFTG1K3O1Lo9Qsnw2Ed06Glj1SqOt7trFDxNO5WYB7+MAMSCoDi33f6J6WuQmJGma4Sgdgbq//AoAA7cyiBucSiVb6X2mgAzBywQ+w5S+pJ8jhppiTXiPXWmRYX3tIxcj5rA3Jb3pXhHNGfG3c2hDAWPmBh2IlB6fxFRpUPEsRRiH+bxvwmCC5geVEdWoguObQS9fdGHgnLZhaF9vLyzbl6YCQXxQzNbisS9MhXvGZUzLmFjxJpM1yxrjs8M56M78U6mwQRfzXkfqCod6AyIO9267XCspSWHCNRT3ETVope+wlW968GMIpsSIZLy1qfJcfylYtyK862bpua8fkZXGaMVn/1Ht3Bxh1DVOb+yfi7d2XjjMlZQKCPxHmeMp4JBWqwtdbRs9fMdDASiE4neeRyx2TzVRpzTAY49iEm2wHUlEe2JUk5eDRqHxU5ruQpL1O02EQ4PVWyvyW/1D+PzLbWxdwYr22ZoLL3mMTmCvz68dJNc+onLGFOizMkYWlpf5D+VKxF19JIH4f+PhWYz00=
